# Generated by Django 3.1.4 on 2021-01-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='books',
            name='review',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
