# Generated by Django 3.1.4 on 2021-01-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210101_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='review',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
