# Generated by Django 3.1.4 on 2021-01-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210101_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
