# Generated by Django 3.1.4 on 2021-01-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_books_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bestSale',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='discount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
